Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: proj-pau-s3-1
      WebsiteConfiguration:
        IndexDocument: translation_tool.html
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: false
        RestrictPublicBuckets: false
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
            BucketKeyEnabled: true
